### ISSUE TITLE
can't add current file

### ISSUE THREAD

**Issue by avimar** [albizures/vscode-gitkit#1]
the output shows this:
I'm running on windows, but the built-in git stuff works.
I'm really missing the "commit the changes on this screen"...
Thanks!

`Error: spawn git ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by albizures** [comment]
Are you sure you have correctly installed git in the cmd?
Because I think is the only way you can get this error.
I don't know how to reproduce the error. I've been testing in windows and all is fine.

**Comment by avimar** [comment]
@albizures Thanks for checking!
When I installed VScode, I didn't have to set up a git path at all for the built-in git to work and push with my saved SSH credentials.

I set the path in settings.json to `"git.path": "C:\\Program Files\\Git\\bin\\git.exe"` and now.. I don't see any error nor any output for gitkit status, gitkit add current file... now what?

Is there a way to send you more debugging information?

**Comment by albizures** [comment]
Sorry for the late answer, i've been very busy
Adding the git path to vscode shouldn't fix the error.
Make sure you have git in the environment variables
![gitpath](https://cloud.githubusercontent.com/assets/6843073/17467192/cbe64cfc-5cd8-11e6-8e36-f33f1478e789.JPG)
